map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 1.25

robot_radius: 0.3
inflation_radius: 0.65

observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: hokuyo,
  data_type: LaserScan,
  topic: /robo/laser/scan,
  marking: true,
  clearing: true
}
