global_costmap:
   global_frame: /map
   robot_base_frame: robot_footprint
   update_frequency: 3.0
   publish_frequency: 4.0
   width: 3000.0
   height: 3000.0
   resolution: 0.05
   static_map: true
   rolling_window: false
