Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder ".", "/host"
  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory and the number of CPU's allocated on the VM:
    vb.memory = "4000"
    vb.cpus = 2

    # Customize the amount of video RAM for the VM, over 256MB causes instability issues
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end

  # ------------------------------------- SSH Rules ----------------------------------------
  # Enables x11 forwarding over ssh
  config.ssh.forward_x11 = true

  # ------------------------------------ Provisioning -------------------------------------
  #Update
  config.vm.provision "shell", inline: "apt-get update"

  # Install desktop for UI
  config.vm.provision "shell", inline: "apt-get -y install --no-install-recommends ubuntu-desktop"

	# Install gnome-terminal
  config.vm.provision "shell", inline: "apt-get -y install gnome-terminal"

  # Install all ROS dependen      cies and environment stuff for development on VM
  config.vm.provision "shell", path: "ros-bootstrap.sh"

  # Correct RosDep permissions
  config.vm.provision "shell", inline: "rosdep fix-permissions"
  config.vm.provision "shell", inline: "rosdep update", privileged: false

  # Get Xauth for X11 forwarding
  config.vm.provision "shell", inline: "apt-get install xauth"

end
