global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 3.0
   publish_frequency: 5.0
   width: 2912.0
   height: 2496.0
   resolution: 0.05
   static_map: true
   rolling_window: false
